ERROR | 2022-06-27 12:38:12,261 | main.py:40 | BOT WAS STARTED
NoneType: None
